output "bucket_name" {
  value       = aws_s3_bucket.s3_bucket.id
  description = "The name of the S3 bucket generated by this module."
}

output "dynamodb_table_name" {
  value       = aws_dynamodb_table.dynamodb_table.name
  description = "The name of the DynamoDB table generated by this module."
}
