output "bucket_name" {
  value       = module.s3_backend.bucket_name
  description = "The name of the S3 bucket generated by this module."
}

output "dynamodb_table_name" {
  value       = module.s3_backend.dynamodb_table_name
  description = "The name of the DynamoDB table generated by this module."
}
